# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowTable(object):
    def setupUi(self, windowTable):
        windowTable.setObjectName("windowTable")
        windowTable.resize(373, 285)
        self.gridLayout = QtWidgets.QGridLayout(windowTable)
        self.gridLayout.setObjectName("gridLayout")
        self.save = QtWidgets.QPushButton(windowTable)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 1, 0, 1, 1)
        self.custom_Matrix = QtWidgets.QTableWidget(windowTable)
        self.custom_Matrix.setRowCount(0)
        self.custom_Matrix.setColumnCount(0)
        self.custom_Matrix.setObjectName("custom_Matrix")
        self.custom_Matrix.horizontalHeader().setVisible(False)
        self.custom_Matrix.horizontalHeader().setHighlightSections(False)
        self.custom_Matrix.verticalHeader().setVisible(False)
        self.custom_Matrix.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.custom_Matrix, 0, 0, 1, 1)

        self.retranslateUi(windowTable)
        QtCore.QMetaObject.connectSlotsByName(windowTable)

    def retranslateUi(self, windowTable):
        _translate = QtCore.QCoreApplication.translate
        windowTable.setWindowTitle(_translate("windowTable", "Custom Matrix"))
        self.save.setText(_translate("windowTable", "Save"))
        
